### ISSUE TITLE
Cli migrating from j2.5.28 to j3.4.4

### ISSUE THREAD

**Issue by ghiamar** [fastslack/jUpgradePro#22]
Hi! After correct setup of the cli interface, I'm getting some kind of error on category migration.

`{"number":500,"text":"UnexpectedValueException: JTableCategory::moveByReference(1, last-child, 35) parenting to child. in \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/joomla\/table\/nested.php:338\nStack trace:\n#0 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/joomla\/table\/nested.php(840): JTableNested->moveByReference(1, 'last-child', '35')\n#1 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/legacy\/table\/category.php(238): JTableNested->store(false)\n#2 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/matware\/jupgrade\/category.php(236): JTableCategory->store()\n#3 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/matware\/jupgrade\/schemas\/2.5\/categories.php(143): JUpgradeproCategory->insertCategory(Array)\n#4 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/matware\/jupgrade\/jupgrade.php(275): JUpgradeproCategories->dataHook(Array)\n#5 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/matware\/jupgrade\/jupgrade.php(193): JUpgradepro->setDestinationData()\n#6 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/matware\/jupgrade\/category.php(123): JUpgradepro->upgrade()\n#7 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/libraries\/matware\/jupgrade\/schemas\/2.5\/categories.php(79): JUpgradeproCategory->upgrade()\n#8 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/j3\/administrator\/components\/com_jupgradepro\/models\/migrate.php(55): JUpgradeproCategories->upgrade()\n#9 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/cli\/jUpgradeProCli\/jUpgradeProCli(188): JUpgradeproModelMigrate->migrate('categories', false)\n#10 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/cli\/jUpgradeProCli\/jUpgradeProCli(134): jUpgradeProCli->migrateCore()\n#11 \/var\/www\/clients\/client1\/web2\/web\/jupgradecli\/cli\/jUpgradeProCli\/jUpgradeProCli(281): jUpgradeProCli->execute()\n#12 {main}"}`

What can I do?

Thanks!

**Comment by fastslack** [comment]
@ghiamar please contact me to support@matware.com.ar and if its possible aens me the old 2.5 database backup. I need to test it in my local

**Comment by fastslack** [comment]
*send
